version: '1'

services:
    db:
        build: 
            context: ./Docker/mysql
            args:
                mysql_version: ${MYSQL_VERSION}
        container_name: database
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports: 
            - "3306:3306"
        restart: always
    
    php:
        build: 
            context: ./Docker/php
            args: 
                php_version: ${PHP_VERSION}
        container_name: php-apache
        ports: 
            - "${PHP_PORT}:80"
        volumes: 
            - ./www:/var/www/html
        links: 
            - db